export const throwError = () => {
  throw new Error("Error (dynamic) from worker two");
};
